upimage:
  home: '/upimage-home'
  host: '${upimage_host}'

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
