name: ci/cd

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          chmod a+x ./gradlew
          ./gradlew test

  tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Read upimage version
        run: |
          chmod a+x ./gradlew
          echo "UPIMAGE_VERSION=$(./gradlew properties | grep -e ^version | grep -Po \\d\.\\d\.\\d\*)" >> $GITHUB_ENV

      - name: Read latest tag
        run: echo "TAG=$(git tag -l v${{ env.UPIMAGE_VERSION }})" >> $GITHUB_ENV

      - name: Verify version
        if: ${{ env.TAG != '' }}
        run: exit 1

      - name: Create release with tag
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.UPIMAGE_VERSION }}
          release_name: v${{ env.UPIMAGE_VERSION }}

      - name: Set upload url
        run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

      - name: Pulish
        uses: devecor/upimage/.github/workflows/reuseable-publish-linux-native.yaml@${{ github.ref }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}