name: ci/cd

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build
        run: |
          chmod a+x ./gradlew
          ./gradlew build

      - name: Share jacoco test report with other jobs
        uses: actions/upload-artifact@v2
        with:
          name: jacoco_test_report
          path: build/reports/jacoco/test/jacocoTestReport.csv

  tag:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Read upimage version
        run: |
          chmod a+x ./gradlew
          echo "UPIMAGE_VERSION=$(./gradlew properties | grep -e ^version | grep -Po \\d\.\\d\.\\d\*)" >> $GITHUB_ENV

      - name: Read latest tag
        run: echo "TAG=$(git tag -l v${{ env.UPIMAGE_VERSION }})" >> $GITHUB_ENV

      - name: Set upload url
        run: echo "${{ steps.create_release.outputs.upload_url }}" > upload_url.txt

      - name: Share upload url with other jobs
        uses: actions/upload-artifact@v2
        with:
          name: upload_url
          path: upload_url.txt

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get test report
        uses: actions/download-artifact@v2
        with:
          name: jacoco_test_report

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv

      - name: Bump up docker image version
        run: |
          npm install js-yaml
          node .github/scripts/bump-version-yaml.js docker-compose.yml ${{ env.UPIMAGE_VERSION }}
          git add docker-compose.yml
          git add .github/badges
          ls .github/badges
          git config user.name "awesome"
          git config user.email "awesome@github.com"
          git commit -m "Bump image version: devecor/upimage:${{ env.UPIMAGE_VERSION }}"
#          git push